### PR TITLE
Fix for entry link synchronization when offline caching

### PR DESCRIPTION
**Pull request by jasonmgeorge**
Updated CDAEntry to fully synchronize nested entry links after initial synchronization.

The updates impact the resolver in the `resolveLinksInDictionary:` method. Previously cached entries were not synchronizing linked entries in the field dictionary properly. This was due to resource.fetched returning true for previously fetched - but not synced - field items.

Invoked from the `for (CDAResource* resource in array) {}`  loop within `resolveLinksInDictionary:` below.
`-(NSDictionary*)resolveLinksInDictionary:(NSDictionary*)dictionary
                      withIncludedAssets:(NSDictionary*)assets
                                 entries:(NSDictionary*)entries
                              usingBlock:(CDAResource* (^)(CDAResource* resource, NSDictionary* assets,
                                                           NSDictionary* entries))resolver {
    NSMutableDictionary* fields = [dictionary mutableCopy];
    
    [dictionary enumerateKeysAndObjectsUsingBlock:^(NSString* key, id value, BOOL *stop) {
        CDAField* field = [self.contentType fieldForIdentifier:key];
        
        if (field.type == CDAFieldTypeArray && [value isKindOfClass:[NSArray class]]) {
            NSArray* array = value;
            
            if (array.count > 0 && CDAClassIsOfType([[array firstObject] class], CDAResource.class)) {
                NSMutableArray* newArray = [@[] mutableCopy];
                
                for (CDAResource* resource in array) {
                    CDAResource* possibleResource = resolver(resource, assets, entries);
                    [newArray addObject:possibleResource ?: resource];
                }
                
                fields[key] = [newArray copy];
            }
        }
        
        if (field.type == CDAFieldTypeLink && CDAClassIsOfType([value class], CDAResource.class)) {
            CDAResource* possibleResource = resolver(value, assets, entries);
            
            fields[key] = possibleResource ?: value;
        }
    }];
    
    return [fields copy];
}`

### CODE REVIEW

**Comment by neonichu** [comment]
This looks good to me, but we'd need the same behaviour for `CDAAsset` as well I think. Would be great if you could add that. 

If you can think of a good succinct test case, that would also be appreciated, but not strictly necessary.

**Comment by jasonmgeorge** [comment]
I'll have to dig in on `CDAAsset`. I thought the same, however, assets are synching properly without the `updatedAt` inspection in my testing. I am unsure why this might be the case.

**Comment by jasonmgeorge** [comment]
I found a test case that would cause assets to fail to sync as well. I added code to sync assets - not sure why CI is failing, `testNoLongerExistingLinksGetDeletedOnSync` succeeds on my machine.

I also wrote unit tests for entry and asset synchronization. They require test data I created that would need to be added to the Data submodule. I haven't quite wrapped my head around how to submit submodule changes for a pull request, so I have not committed the unit tests. Any suggestions on how to incorporate additional .json test data?

**Comment by neonichu** [comment]
The "Data" submodule is based off this branch <https://github.com/contentful/contentful.objc/tree/Fixtures>, you should be able to create your own branch based on that and submit a separate PR for it.

**Comment by neonichu** [comment]
@jasonmgeorge I'm happy to pick up the PR and add the tests myself if that would help — I'd really like to merge this

**Comment by jasonmgeorge** [comment]
@neonichu Apologies. I missed your message last week. I'll try to commit my tests today. I will follow up if I have issues. Thanks.

**Comment by neonichu** [comment]
Looks good, thanks 👍

**Pull request merged**
